Index callbacks to avoid linear searchs
upsert/lutron-caseta-pro pull request #67
Opened 2020-11-14 22:44 UTC by bdraco

2020-11-15 17:03 UTC, upsert requested changes
Please deconflict the code now that upsert/lutron-caseta-pro#66 is merged.

2020-11-15 17:54 UTC, bdraco commented
> Please deconflict the code now that #66 is merged.

Fixed conflict, ran though isort, ran though black.

Retested to make sure pico remotes still work. 👍

2020-11-21 18:45 UTC, upsert approved these changes
- Reviewed the code changes.
- Tested against Home Assistant `dev` branch and devices and sensors appear to be working as expected.

2020-11-21 18:45 UTC, merged

2020-11-21 18:46 UTC, bdraco commented
Thanks 👍